name: e2e-model
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.7
  - pip
  - pip:
    - pdf2image
    - opencv-python==4.5.1.48
    - Pillow==9.0.0
    - requests
    - jsonpickle
    - matplotlib
    - dataclasses_json
    - torch==1.13.1
    - torchvision==0.14.1
    - pytorch-lightning==1.9.0
    - transformers==4.26.0
    - timm==0.6.12
    - ../donut
    - ../../libs/webapp
