name: e2e-model
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.7
  - pip
  - pip:
    - pdf2image==1.16.0
    - opencv-python==4.5.1.48
    - Pillow==9.0.0
    - requests
    - jsonpickle
    - matplotlib
    - dataclasses_json
    - torch==1.11.0
    - torchvision==0.12.0
    - pytorch-lightning==1.6.4
    - transformers==4.11.3
    - timm==0.5.4
    - ../donut
    - ../../libs/webapp
